### ISSUE TITLE
Can't generate project

### ISSUE THREAD

**Issue by digitalsadhu** [t4t5/november-cli#1]
No matter where I run the following command from:

```
november new my-app
```

I always get this error:

```
You're trying to create a new November project inside an existing one! Did you mean to use `november generate my-app?
```

**Comment by t4t5** [comment]
Ah. That must be because there's a package.json somewhere in one of your top directories.

The way November tries to determine if you're already in a November project right now is to check if there's a `package.json`-file, which is obviously a little flawed. :) Will fix it soon so that it checks other things in addition to that.

**Comment by digitalsadhu** [comment]
Ah yea, I think I know why then. I think theres a package.json in my projects folder (of which my my-app folder is a child)

Cheers

**Comment by digitalsadhu** [comment]
Yup, that sorted it.
